### ISSUE TITLE
Mediaplayer playback doesn't work

### ISSUE THREAD

**Issue by vicpinm** [VitamioCustom/Vitamio-5.0.0#2]
I can't play any audio, from local file, resource, or http/rtmp link. I'm using the example project and it doesn't work. When I play any audio with MediaPlayer, it appears to work fine, the log outputs this:

Vitamio[5.0.0][Player]: Vitamio Version 5.0.0 
Vitamio[5.0.0][Player]: Application package name: io.vov.vitamio.demo
...
Vitamio[5.0.0][Player]: prepare
Vitamio[5.0.0][Player]: PREPARE SIG: 0
Vitamio[5.0.0][Player]: start
Vitamio[5.0.0][Player]: THREAD PREPARE START
Vitamio[5.0.0][Player]: THREAD PREPARE ATTACHED
itamio[5.0.0][Player]: Copyright (c) YIXIA...
Vitamio[5.0.0][Player]: OPEN FILE /storage/emulated/0/ivoox/test.mp3
Vitamio[5.0.0][Player]: [mp3 @ 0xb38c9600] Estimating duration from bitrate, this may be inaccurate
Vitamio[5.0.0][Player]: Input #0, mp3, from '/storage/emulated/0/ivoox/test.mp3':
Vitamio[5.0.0][Player]:   Duration: 
Vitamio[5.0.0][Player]: 00:19:08.34
Vitamio[5.0.0][Player]: , start: 
Vitamio[5.0.0][Player]: 0.000000
...
Vitamio[5.0.0][Player]: OPEN CODEC mp3
Vitamio[5.0.0][Player]: OPEN STREAM AUDIO BEGIN
Vitamio[5.0.0][Player]: THREAD AUDIO_DECODE START

But I cant hear anything in any device I have test...
Any suggestions?
(I have been using Vitamio 4.2 without problems)

**Comment by MythodeaLoL** [comment]
Sorry, this is just a mirror, is not an official repository of version 5.0.0, there is no official repository at github, so it's a little hard to help you get to this version of vitamio.
