### ISSUE TITLE
Fatal Exception while playing HLS Stream

### ISSUE THREAD

**Issue by visakhvj** [VitamioCustom/Vitamio-5.0.0#4]
While playing HLS stream with the latest version of Vitamio (5.0.0) got the following fatal exception

Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 31095.

Mainly this issue occurred while buffering starts. In Vitamio 4.0 version it was working perfectly. But due to some security vulnerability with the older version, we need to upgrade to this latest version. But it have this issue.

Could you please help me in solving this issue?

**Comment by danielto** [comment]
Hi, I have the same issue ona device with android api 15. The HLS stream is working on api 21.

Were you able to fix it?
Thank you.

**Comment by visakhvj** [comment]
No. I won't able to fix this issue. I switched to Google EXO player and now everything is working as expected.

**Comment by danielto** [comment]
Thank you for you reply. EXO player is definitely better choice, but it is not working with API 15 so it is not suitable for my project.
