### ISSUE TITLE
Vitamio 5.0 Audio problem with video streaming. How can I fix it?

### ISSUE THREAD

**Issue by nuhkoca** [VitamioCustom/Vitamio-5.0.0#5]
Hello, I am facing with a problem in Android. I am using Vitamio 5.0. I can play video but cannot play audio. How can I fixt it? Please help me. Thanks.

**Comment by MythodeaLoL** [comment]
Please, use official [vitamio issue report](https://github.com/yixia/VitamioBundle/issues/), all vitamio users can help u, fast.

##### and read this topic: https://github.com/yixia/VitamioBundle/issues/337

**Comment by dorkden** [comment]
Vitamio 5.0, i face that problem too, first i used vitamio VideoView. it work but no audio. and i use vitamio MediaPlayer with surfaceView instead of VideoView.
it work find for me but i have to write more code. hope it help!
