### ISSUE TITLE
Fail to play video with https using tls 1.2

### ISSUE THREAD

**Issue by poetzhangzi** [VitamioCustom/Vitamio-5.0.0#8]
Although openssl 1.0.2 seems to support tls 1.2. However, I still fail to play video with tls 1.2 protocol. Now I put a video on my server. (https://zhanghomeserver.ddnsfree.com/~Zhang/Data/Samples//Movies/movsample.mov). 
It can be directly played by browser, libvlc library of android and vlckit of iOS.
I think the problem is the openssl library or ffmpeg library.

**Comment by MythodeaLoL** [comment]
@poetzhangzi This repository is just a mirror, the vitamin is very outdated, I recommend migrating your project to ijkplayer, it is the most up to date player for now. Good luck.
